# Generated by Django 5.2.7 on 2026-02-24 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0002_angajat'),
    ]

    operations = [
        migrations.AddField(
            model_name='angajat',
            name='angajare',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='angajat',
            name='departament_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='angajati', to='CompanyApp.departament'),
        ),
        migrations.AddField(
            model_name='angajat',
            name='manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordonati', to='CompanyApp.angajat'),
        ),
        migrations.AddField(
            model_name='angajat',
            name='salariu',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='angajat',
            name='vechime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='departament',
            name='manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamente_conduse', to='CompanyApp.angajat'),
        ),
    ]
