# Generated by Django 5.2.7 on 2026-02-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0004_rename_departament_id_angajat_departament_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departament',
            name='manager',
        ),
        migrations.AddField(
            model_name='departament',
            name='manager_id',
            field=models.IntegerField(null=True),
        ),
    ]
